In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
def isValid(A,B):
    if len(A[0]) == len(B):
        return True
    else:
        return False

In [5]:
def matrix_multiply(A,B):
    if isValid(A,B):
        C = np.zeros((len(A),len(B[0])))
        for i in range(len(A)):
            for j in range(len(B[0])):
                for k in range(len(B)):
                    C[i][j] += A[i][k] * B[k][j]

        return C

In [6]:
def matrix_multiply_2(A,B):
    if isValid(A,B):
        return np.dot(A,B)
    else:
        return None

In [7]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: [[102. 108. 114.]
 [246. 261. 276.]
 [390. 414. 438.]
 [534. 567. 600.]]
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]

In [8]:
def mean(x):
  total_numbers = len(x)
  total_sum = sum(x)
  mean = total_sum / total_numbers
  return mean

In [9]:
def standard_deviation(x):
  mean_value = mean(x)
  total_numbers = len(x)
  squared_deviations = [(x_i - mean_value)**2 for x_i in x]
  variance = sum(squared_deviations) / total_numbers
  standard_deviation = variance ** 0.5
  return standard_deviation

In [10]:
def zscore_normalisation(x):
  mean_value = mean(x)
  standard_deviation_value = standard_deviation(x)
  zscores = [(x_i - mean_value) / standard_deviation_value for x_i in x]
  return zscores

In [11]:
def zscore_normalisation_2(x):
  x_array = np.array(x)
  mean_value = np.mean(x_array)
  standard_deviation_value = np.std(x_array)
  zscores = (x_array - mean_value) / standard_deviation_value
  return zscores

In [12]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

Result without using numpy: [-1.0675326683028088, -0.9974539373420117, -0.9974539373420117, -0.8105773214465528, -0.41346451266870277, -0.06307085786471743, 0.3106823739262003, 0.9180313755864415, 1.2217058764165623, 1.8991336090376005]
Result using numpy: [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [13]:
def sigmoidfn(x):
  return 1 / (1 + np.exp(-x))

In [14]:
def derivative(x):
  fn = sigmoidfn(x)
  return fn * (1 - fn)

In [15]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

x on applying sigmoid activation fn is: [[0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ]]
x on applying derivative of sigmoid activation fn is: [[1.23379350e-04 1.04993585e-01 6.64805667e-03 2.50000000e-01
  2.50000000e-01]
 [9.10221180e-04 6.64805667e-03 2.50000000e-01 2.50000000e-01
  2.50000000e-01]]

In [16]:
superheated_vapor_properties = pd.read_csv('superheated_vapor_properties.csv')
superheated_vapor_properties

                                                                                                                                                                                                                                                                                                                                                                                                           <<<<<<< HEAD
Pressure                                         Property Liq_Sat Vap_Sat 75.0000     100.0000    125.0000    150.0000    175.0000    200.0000    220.0  225.0000    240.0  250.0000    260.0  275.0  280.0  290.0  300.000    320.0  325.0  340.0000  350.0000    360.000  375.0  380.0000  400.0000    425.0000  450.0000    475.0000  500.0000    525.0000  550.0000    575.000  600.0000    625.0000       650.0000
1                                                V        1       129200  160640.0000 172180.0000 183720.0000 195270.0000 206810.0000 218350.0000 NaN    229890.0000 NaN    241430.0000 NaN    NaN    NaN    NaN    264500.000 NaN    NaN    NaN       287580.0000 NaN      NaN    NaN       310660.0000 NaN       333730.0000 NaN       356810.0000 NaN       379880.0000 NaN      402960.0000 NaN         426040.0000
                                                 U        29.334  2385.2  2480.8000   2516.4000   2552.3000   2588.5000   2624.9000   2661.7000   NaN    2698.8000   NaN    2736.3000   NaN    NaN    NaN    NaN    2812.300   NaN    NaN    NaN       2889.9000   NaN      NaN    NaN       2969.1000   NaN       3049.9000   NaN       3132.4000   NaN       3216.7000   NaN      3302.6000   NaN           3390.3000
                                                 H        29.335  2514.4  2641.5000   2688.6000   2736.0000   2783.7000   2831.7000   2880.1000   NaN    2928.7000   NaN    2977.7000   NaN    NaN    NaN    NaN    3076.800   NaN    NaN    NaN       3177.5000   NaN      NaN    NaN       3279.7000   NaN       3383.6000   NaN       3489.2000   NaN       3596.5000   NaN      3705.6000   NaN           3816.4000
                                                 S        0.106   8.9767  9.3828      9.5136      9.6365      9.7527      9.8629      9.9679      NaN    10.0681     NaN    10.1641     NaN    NaN    NaN    NaN    10.345     NaN    NaN    NaN       10.5133     NaN      NaN    NaN       10.6711     NaN       10.8200     NaN       10.9612     NaN       11.0957     NaN      11.2243     NaN             11.3476
...                                                                                                                                                                                                                                                                                                                                                                                                                 ...
11400                                            V        1.504   15.284  NaN         NaN         NaN         NaN         NaN         NaN         NaN    NaN         NaN    NaN         NaN    NaN    NaN    NaN    NaN        NaN    NaN    17.6220   NaN         19.495   NaN    21.0790   22.4920     24.1040   25.5990     27.0100   28.3590     29.6610   30.9250     32.160   33.3700     34.5600         35.7330
                                                 U        1450    2527.2  NaN         NaN         NaN         NaN         NaN         NaN         NaN    NaN         NaN    NaN         NaN    NaN    NaN    NaN    NaN        NaN    NaN    2622.7000 NaN         2697.000 NaN    2758.4000 2812.3000   2873.1000 2929.4000   2982.6000 3033.9000   3083.9000 3133.1000   3181.900 3230.4000   3278.8000     3327.2000
                                                 H        1467.2  2701.5  NaN         NaN         NaN         NaN         NaN         NaN         NaN    NaN         NaN    NaN         NaN    NaN    NaN    NaN    NaN        NaN    NaN    2823.6000 NaN         2919.300 NaN    2998.7000 3068.7000   3147.9000 3221.2000   3290.5000 3357.2000   3422.1000 3485.7000   3548.500 3610.8000   3672.8000     3734.6000
>>>>>>> 26c7cfb764a3f067c96a00685665a6238c971a2b NaN      NaN     NaN     NaN         NaN         NaN         NaN         NaN         NaN         NaN    NaN         NaN    NaN         NaN    NaN    NaN    NaN    NaN        NaN    NaN    NaN       NaN         NaN      NaN    NaN       NaN         NaN       NaN         NaN       NaN         NaN       NaN         NaN      NaN         NaN                 NaN
11400                                            S        3.4575  5.5357  NaN         NaN         NaN         NaN         NaN         NaN         NaN    NaN         NaN    NaN         NaN    NaN    NaN    NaN    NaN        NaN    NaN    5.7383    NaN         5.892    NaN    6.0156    6.1211      6.2367    6.3399      6.4341    6.5218      6.6043    6.6828      6.758    6.8304      6.9004           6.9683

[1091 rows x 1 columns]

In [17]:
df = pd.DataFrame(superheated_vapor_properties)
df.shape

(1091, 1)

In [18]:
df = pd.DataFrame(superheated_vapor_properties)
column_name = df.columns.to_numpy()
column_name

array(['<<<<<<< HEAD'], dtype=object)

In [19]:
null_totals = df.isnull().sum()
null_totals

<<<<<<< HEAD    2
dtype: int64

In [20]:
column_with_max_missing_value = null_totals.idxmax()
column_with_max_missing_value

'<<<<<<< HEAD'